### ISSUE TITLE
freedom shim

### ISSUE THREAD

**Issue by agallant** [freedomjs/freedom-social-firebase#1]
Per chats w/Lucas, Will, and Ray, we want to make sure that Firebase is supported as a freedom module from the get-go. This requires figuring out what functionality is missing to write an appropriate shim and get the pieces fit together. I'm creating this issue to begin tracking this effort, with the intention of fleshing out as we find what specific calls need a shim of some sort.

**Comment by dborkan** [comment]
+1, I'm hoping we can do some work on this issue this week at the coding
party.

**Comment by agallant** [comment]
(Documenting here for wider availability/my reference.)

There's a test repo that tries to connect to Firebase within freedom (with a Chrome extension): https://github.com/dborkan/freedom-firebase-test

The freedom module test fails at: https://github.com/dborkan/freedom-firebase-test/blob/master/socialprovider.js#L39

The most distilled way to reproduce it is to load it as a Chrome extension, get the console into the innermost webworker (w/Firebase in scope), then run:

```
var baseRef = new Firebase( "https://popping-heat-4874.firebaseio.com");
baseRef.authWithOAuthToken("facebook",
'CAACTRbmvZCKUBAP66Sf5s6BZC6JThs2vTcYfvvktAbZCfvZBZAFXOIatqLpEXiOsda78QQ2rJAWuQWKoXRyVVx4VcezuAwnyFEDydmhU44u3nyCnHpKzg6Y9yELN5bAYWflrZCzFFrvUa6k6zErIZAQcEMit7xZAF1EAYeZCdO75iihuQXjmjNK6NDWET5YX7dKcaW4JD9a9xZAQZDZD',
function(error, authData) { if (error) { console.log("error!"); console.log(error); }
else { console.log(authData); }});
```

Which results in:

```
VM51:2 error!
VM51:2 Error: Unable to contact the Firebase server.
{code: "NETWORK_ERROR", stack: (...), message: "Unable to contact the Firebase server."}
code: "NETWORK_ERROR"message: "Unable to contact the Firebase server."stack: (...)get stack:
function () { [native code] }set stack: function () { [native code] }arguments: nullcaller: nulllength: 1name:
""prototype: StackTraceSetter__proto__: function Empty() {}<function scope>__proto__: d
```

Relevant Firebase API doc: https://www.firebase.com/docs/web/api/firebase/authwithoauthtoken.html

Relevant bit of obfuscated JS: https://github.com/freedomjs/freedom-social-firebase/blob/master/firebase.js#L129

However, I'm having a bit of trouble finding unobfuscated code relating to that - Firebase's repos appear to be more of ecosystem/tools/bindings. I'll keep poking, but if you know how to dive deeper into Firebase let me know - thanks!

UPDATE: Found it - https://github.com/firebase/firebase-bower/blob/master/firebase-debug.js

**Comment by agallant** [comment]
Diving deeper, the Firebase calls go `authWithOAuthToken -> authWithCredential -> authWithTransports_  -> requestWithTransports_`

The error is being surfaced on this line: https://github.com/firebase/firebase-bower/blob/master/firebase-debug.js#L9200

So any needed shim here likely has to do with transport/transportObj, which looks to be a separate little rabbithole. Will continue digging...

**Comment by willscott** [comment]
Suggestion: push to https://github.com/dborkan/freedom-firebase-test to
switch to firebase-debug.js so we can keep current progress updated in that
demo.

**Comment by agallant** [comment]
SGTM: https://github.com/dborkan/freedom-firebase-test/pull/1

**Comment by agallant** [comment]
So I've pinpointed it down to a more vanilla-ish JS bug: https://github.com/soycode/freedom-firebase-test/blob/04f14daa5cf45a8965e25b335403834ae47a6a53/firebase-debug.js#L8813

With the logging, this ends up throwing what I labeled an "outer network error", i.e. it fails on exactly that line (the "created js document" log line doesn't run). The error itself is `ReferenceError: document is not defined` - so basically, Firebase seems to expect "document" to be in scope, and it's not.

I've not fully grokked _why_ it's writing a script tag in this context, but I think once we figure that out we ought to be able to come up with a reasonable fix.

**Comment by willscott** [comment]
node-xmpp has the same issues. solution seems to be to have a script load
before firebase that defines `window` and `document` with needed properties.

**Comment by dborkan** [comment]
It looks like Firebase is using script tags to make JSONP requests.  For me its making a request to 

```
https://auth.firebase.com/v2/popping-heat-4874/auth/facebook/token?access_token=CAACTRbmvZCKUBAP66Sf5s6BZC6JThs2vTcYfvvktAbZCfvZBZAFXOIatqLpEXiOsda78QQ2rJAWuQWKoXRyVVx4VcezuAwnyFEDydmhU44u3nyCnHpKzg6Y9yELN5bAYWflrZCzFFrvUa6k6zErIZAQcEMit7xZAF1EAYeZCdO75iihuQXjmjNK6NDWET5YX7dKcaW4JD9a9xZAQZDZD&v=js-2.0.4&transport=json&suppress_status_codes=true&callback=__firebase_auth_jsonp.fn142360441647926525
```

and you can see the callback parameter __firebase_auth_jsonp.fn142360441647926525 (from the obfuscated version, maybe this has a better name in the debug version)

Some options I can think of:
- modify Firebase code somehow to not do JSONP
- make a shim for document.createElement that supports JSONP

Any other ideas?

**Comment by agallant** [comment]
Per chat w/Will, it sounds like we need (1) core.jsonp, and (2) possibly some Firebase/Facebook specific shim to ensure the setup uses core.jsonp instead of trying to write the script tag as it does. I'll start by looking at the former (https://github.com/freedomjs/freedom/issues/224).

**Comment by ryscheng** [comment]
Probing around to see if there's some internal flag to allow use of CORS or WebSockets. We already force the Firebase library to use WebSockets, so I don't understand why we'd need JSONP.

**Comment by ryscheng** [comment]
Also, I don't understand how JSONP would work in this environment anyway. The reason we moved to WebSockets was exactly for this reason. Chrome apps cannot load scripts from random origins.

**Comment by willscott** [comment]
This isn't firebase, but rather the facebook auth.

**Comment by willscott** [comment]
chrome app implementation would probably need to load the jsonp'ed script
into a https://developer.chrome.com/apps/tags/webview.

**Comment by dborkan** [comment]
Ray and I are kinda confused.  I'm able to get Firebase code working in a
Chrome App background page, but not a Freedom web worker.  But shouldn't
the script tag used for JSONP be blocked due to the content_security_policy
of Chrome Apps?  Maybe there is some other reason why Firebase in the
freedom module is hitting the JSONP code but the background page Firebase
isn't (I would think that using WebSockets would mean we shouldn't need
JSONP anyways)?

(Sorry, just saw Ray's post and realized mine is kind of a duplicate)

**Comment by agallant** [comment]
Hrm, looks like maybe it tries XHR first, and falls back to JSONP: https://github.com/soycode/freedom-firebase-test/blob/04f14daa5cf45a8965e25b335403834ae47a6a53/firebase-debug.js#L9070

So maybe just add core.xhr permissions to the freedom module?

**Comment by dborkan** [comment]
XMLHttpRequest still looks to be available in the Freedom modules (I thought it wasn't going to be disabled until freedom 0.7?), so I'm not sure yet why that would be failing..

**Comment by agallant** [comment]
Looks like Firebase itself is deciding that XMLHttpRequest is not available based on this logic: https://github.com/soycode/freedom-firebase-test/blob/04f14daa5cf45a8965e25b335403834ae47a6a53/firebase-debug.js#L8504

After logging, we're failing this condition: !!window["XMLHttpRequest"]

So I'll just put something that makes that true in socialprovider.js and see how things go.

**Comment by dborkan** [comment]
Related to that, I'm noticing that in Freedom modules, XMLHttpRequest is defined (to the usual native code function), but window["XMLHttpRequest"] is undefined..  Is there any way we can get all global scoped variables to also be set on the window object, like in a typical browser tab?

**Comment by agallant** [comment]
And it worked, kinda: https://github.com/soycode/freedom-firebase-test/commit/8fc630d73524327c9ab42437fe6037932889ef81

I now get to "Login Failed! Error: Invalid authentication credentials provided." instead of the former connection error. That may be because I just cloned the repository but didn't think at all about setting up my own tokens/etc.

That commit is admittedly sloppy and full of the investigative logging I did, but I'll send a pull request anyway if you want to get it into your test repo. Let me know if you want another pull request later to remove all this logging, but since this is for "test" anyway I figure it's not a big deal either way.

**Comment by dborkan** [comment]
Yay!  Don't worry about logging code for now in freedom-firebase-test.  We'll clean all that up for the later versions of freedom-social-firebase

**Comment by dborkan** [comment]
Just updated the auth token and it worked!!!  I'll start trying to get
freedom-social-firebase working in a freedom module with these changes.

**Comment by dborkan** [comment]
I was just talking with Ray and we believe that the core.websocket shim will still be needed for Firefox.  My plan for Firebase is now:
1. Move the current freedom-social-firebase repo to a freedom module and get that running (able to login, not necessarily fixing all the logic bugs) in Chrome.
2. get freedom-social-firebase working as a freedom module in Firefox (probably requires the core.websocket shim and maybe others)
3. Fix all the outstanding logic bugs in freedom-social-firebase (documented at the top of https://github.com/freedomjs/freedom-social-firebase/blob/master/firebase-social-provider.js)

**Comment by agallant** [comment]
Resolved - see: https://github.com/freedomjs/freedom-social-firebase/pull/5 particularly https://github.com/freedomjs/freedom-social-firebase/pull/5/files#diff-c803e4398a9986a7260b55b46c215b2eR27
